server:
  port: 8091

spring:
  jpa:
    generate-ddl: false
  datasource:
    password: password
    username: user
    url: jdbc:postgresql://localhost:5460/magnit-faq-bot-db?stringtype=unspecified

locale:
  tag: ru-RU

telegram:
  bot:
    username: MagnitFaqChatBot
    token: token

button:
  limit:
    algorithms: 3
    examples: 3
