server:
  port: 8091

spring:
  jpa:
    generate-ddl: false
  datasource:
    password: password
    username: user
    url: jdbc:postgresql://localhost:5460/magnit-faq-bot-db?stringtype=unspecified

locale:
  tag: ru-RU

telegram:
  bot:
    username: MagnitFaqChatBot
    token: 6604174182:AAHURc6pABvO4gO-l5zpN82NzvDGHhPJ8kM

button:
  limit:
    algorithms: 3
    examples: 3

rest:
  template:
    read-timeout: 60
    auth-user-service-name: http://localhost:8092

api:
  auth:
    get-roles-by-telegram-id-resource: /v1/user/telegram/%d

category:
  mapping:
    ROLE_ALCOHOL:
      - Алкоголь
    ROLE_TOBACCO:
      - Табак
    ROLE_TEXTILE:
      - Текстиль
    ROLE_PERFUMERY:
      - Парфюмерия
    ROLE_USER:
    ROLE_ADMIN:
      - Алкоголь
      - Табак
      - Текстиль
      - Парфюмерия
